version: 2

runOnDocker: &runOnDocker
  docker:
    - image: circleci/golang:1.11.4
  working_directory: /go/src/github.com/ilgooz/service-location

jobs:
  "test":
    <<: *runOnDocker
    steps:
      - checkout
      - run: GO111MODULE=on go mod download
      - run: GO111MODULE=on go mod vendor
      - run: go test -p 1 -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - "test"